# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 368)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 19, 491, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.small = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.small.setObjectName("small")
        self.gridLayout.addWidget(self.small, 0, 1, 1, 1)
        self.result = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.result.setText("")
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 3, 0, 1, 1)
        self.edit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.edit.setObjectName("edit")
        self.gridLayout.addWidget(self.edit, 0, 0, 3, 1)
        self.change = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.change.setObjectName("change")
        self.gridLayout.addWidget(self.change, 3, 1, 1, 1)
        self.big = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.big.setObjectName("big")
        self.gridLayout.addWidget(self.big, 1, 1, 1, 1)
        self.reverse = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.reverse.setObjectName("reverse")
        self.gridLayout.addWidget(self.reverse, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.small.setText(_translate("Dialog", "Małe"))
        self.change.setText(_translate("Dialog", "Zmień"))
        self.big.setText(_translate("Dialog", "Durze"))
        self.reverse.setText(_translate("Dialog", "Zmień"))
